language: ruby
rvm:
- 2.4.2

cache:
  - bundler

install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source

env:
  global:
    #- NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    # secure: 1f17321c50c71648146da0d69d82acae44fe6697
    api_key:
      secure=02e6d90d7da514a422675f14428dbd3f32fa5372

sudo: false


# Optional:
# disable email notifications about the outcome of your builds
# send slack notifications on success builds
notifications:
  email: true
  slack:
    on_success: always
