exclude:
    - "/vendor/"
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - package.json
    - package-lock.json
    - yarn.lock
    - backups
    - next_steps.md
    - next_steps.css

#Site Settings
title: Cornerstone Community Development Corporation
owner: Cornerstone Community Development Corporation
email: systemadmin@cdccornerstone.org
description: Cornerstone Community Development Corporation (Cornerstone) is a faith-based 501(c) (3), non-profit organization, serving Bergen County, New Jersey, whose purpose is to meet the needs in the community through entrepreneurship, partnership, and education.
url: "https://www.cdccornerstone.org/" #actual site url https://kayceejjay.github.io not CNAME if one used; http://localhost:63342/Cornerstone/Cornerstone/ https://kens-coding-kayceejjay.c9users.io/ in development
baseurl: ""
webmaster: TechHandie Corporation
webmaster_email: admin@techhandie.com
webmaster_url: "https://www.techhandie.com"

#Build Settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

#Key Paths
assets:
    - attachments
    - css
    - fonts
    - images
    - videos

sass:
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules